# For detailed configuration reference documentation, visit:
# https://supabase.com/docs/guides/local-development/cli/config

project_id = "klickit-local"

[api]
enabled = true
port = 54321
schemas = ["public", "dentos_data", "dentos_runtime", "dentos_analytics"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 17

[studio]
enabled = true
port = 54323

[inbucket]
enabled = true
port = 54324

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:5173"
additional_redirect_urls = ["http://127.0.0.1:5173"]
enable_signup = false

[db.seed]
enabled = true
sql_paths = ["./seed.sql"]
